### ISSUE TITLE
Change the Episode status indicator

### ISSUE THREAD

**Issue by avongit** [gpodder/gpodder-bb10#2]
The status of the Episode(Downloaded, Not Downloaded) is shown using a thin vertical line.
This is not visible properly.
Is it possible to put up an image to show if the episode is downloaded.

In earlier versions, there used to be a folder image that indicated that the file is downloaded and it will not be streamed.
Can you please put the image back. This way it is very clear.

Note: I am not expecting any activity/event from the image. Just replace the vertical line with the folder image.

I like the way all the operation are hidden and appear when the episode is touched/Clicked.

**Comment by thp** [comment]
Fixed here: https://github.com/gpodder/gpodder-ui-qml/commit/953905ba3b442402b57d98cea257f4a094c02f41

We now show a small rectangle on the right side of the podcast and episode list. This will be part of the next release.
