### ISSUE TITLE
Cannot Filter Episodes

### ISSUE THREAD

**Issue by avongit** [gpodder/gpodder-bb10#7]
From the home screen, When we select "Filter Episodes" menu option, I get to see all the episodes from all the podcasts.
But I further don't see the any other filter options now.
Earlier I could see a search icon(magnifying glass).

Can you also provide some insight on what exactly "Enqueue episodes in player does"

Device:
Blackberry Q10
OS: 10.2.1.3062

Thanks,
Vinay

**Comment by thp** [comment]
The issue with the button not appearing has been fixed here:

https://github.com/gpodder/gpodder-ui-qml/commit/bc8241e99a721f5f76e6d2a6ed81768e38876cee
