### ISSUE TITLE
Episode listing issue

### ISSUE THREAD

**Issue by avongit** [gpodder/gpodder-bb10#8]
Hi,

I recently subscribed to Planet Money podcast.
(http://www.npr.org/rss/podcast.php?id=510289)

The episodes are not showing properly. 
They are messed-up. 
Please see the screenshots attached. 
![img_20150223_155900](https://cloud.githubusercontent.com/assets/9247578/6326334/9cef326a-bb76-11e4-85cd-2dd1250a3d8d.png)
![img_20150223_155912](https://cloud.githubusercontent.com/assets/9247578/6326338/a68a995e-bb76-11e4-973d-dd2fcf639e58.png)
![img_20150223_155921](https://cloud.githubusercontent.com/assets/9247578/6326347/c04ea786-bb76-11e4-9f0b-2bdc16fd9478.png)

This is not happening with other podcasts that I'm using. 
Ccan you please take a look at it. 

Thanks,
Vinay

**Comment by thp** [comment]
Fixed with https://github.com/gpodder/gpodder-ui-qml/commit/a03ede77f4c09c9677d24f084b5d09316c847520, will be part of the next release.

**Comment by avongit** [comment]
Thank you. That was quick.
So when is this next release expected.
Have you thought of any dates.

Thanks again,
Vinay
